version: '3.8'

services:
  free-render-server:
    build: 
      context: .
      args:
        INSTALL_N8N: ${INSTALL_N8N:-false}
        INSTALL_NGROK: ${INSTALL_NGROK:-true}
    image: free-render-server:latest
    container_name: free-render-server-container
    ports:
      - "80:80"
    environment:
      - N8N_ENABLED=${N8N_ENABLED:-true}
      - NGROK_ENABLED=${NGROK_ENABLED:-false}
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-}
    restart: unless-stopped
